spring:
  application:
        name: spark-base-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/miao_dome?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  data:
    redis:
      database: 4
      password: xing123
      timeout: 30s
      host: 8.155.39.234
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
    port: 8081
    servlet:
      context-path: /sys


logging:
  level:
    sql: debug
    com:
      spark: debug